name: sample workflow
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out the code
        uses: actions/checkout@v3
      - name: Peep the folder
        run: |
            node --version

