name: main workflow
on: push
jobs:
  actor:
    runs-on: ubuntu-latest
    steps:
      - name: Triggered By
        run: echo "Triggered by ${{github.actor}}"
  checkout-install-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out the code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
            npm install
      - name: Build the package
        run: |
            npm run build

