name: sample workflow
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out the code
        uses: actions/checkout@v3
      - name: Peep the folder
        run: |
            echo "Current directory"
            pwd
            echo "List files"
            ls -al
      - name: Install dependencies
        run: npm install
      - name: Build the code
        run: npm run build
      - name: Peep the folder
        run: |
            echo "Current directory"
            pwd
            echo "List files"
            ls -al
      - name: Start the server
        run: npm start

