name: sample workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checks out the code
        uses: actions/checkout@v3
      - name: Installs dependencies
        run: npm install
      - name: Builds project
        run: npm run build
